name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to production
        uses: genietim/ftp-action@releases/v4
        with:
            host: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            localDir: "build"
            remoteDir: "www"